#!/usr/bin/env python3

from subprocess import call
import os
import sys
import signal
import i3ipc

LOCK_FILE = '/tmp/disable-standby-fs.lock'


def check_lock():
    if os.path.isfile(LOCK_FILE):
        print(
            f"Another instance is already running (lock file exists: {LOCK_FILE}).")
        sys.exit(0)
    with open(LOCK_FILE, 'w') as f:
        f.write(str(os.getpid()))


def remove_lock():
    if os.path.isfile(LOCK_FILE):
        os.remove(LOCK_FILE)


def handle_signal(signum, _):
    print(f"Received signal {signum}, removing lock file and exiting.")
    remove_lock()
    sys.exit(0)


def setup_signal_handlers():
    for sig in (signal.SIGINT, signal.SIGTERM, signal.SIGHUP):
        signal.signal(sig, handle_signal)


def find_fullscreen(con):
    # XXX remove me when this method is available on the con in a release
    return [c for c in con.descendants() if c.type == 'con' and c.fullscreen_mode]


def set_dpms(state):
    if state:
        print('setting dpms on')
        call(['xset', 's', 'on'])
        call(['xset', '+dpms'])
    else:
        print('setting dpms off')
        call(['xset', 's', 'off'])
        call(['xset', '-dpms'])


def on_fullscreen_mode(i3, _):
    set_dpms(not len(find_fullscreen(i3.get_tree())))


def on_window_close(i3, _):
    if not len(find_fullscreen(i3.get_tree())):
        set_dpms(True)


def main():
    check_lock()
    setup_signal_handlers()
    try:
        i3 = i3ipc.Connection()
        i3.on('window::fullscreen_mode', on_fullscreen_mode)
        i3.on('window::close', on_window_close)
        i3.main()
    finally:
        remove_lock()


if __name__ == '__main__':
    main()
