require('k1ng.configs.options')
require('k1ng.configs.autocmds')
require('k1ng.configs.commands')
require('k1ng.configs.disable-builtin')
require('k1ng.configs.keymaps')
require('k1ng.configs.usercmds')
require('k1ng.configs.plugin').setup('k1ng.plugins')
